### ISSUE TITLE
this isn't a real issue i just wanted to show you

### ISSUE THREAD

**Issue by Chocobro** [Rafa652/GameChannel#2]
that github has dumb stupid emotes now
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Rafa652** [comment]
I just tried to label this "👌 👌 💯 👌 👀 👀". It doesn't let me.

**Comment by Chocobro** [comment]
HAHA
